env:
  browser: true
  es2021: true
  jest/globals: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins: ["jest"]
rules:
  no-underscore-dangle: ["error", { "allow": ["__filename", "__dirname"] }]
  no-console: 0
  import/extensions: [2, {
            "js": "always"
        }]
